site_name: SYSU SAA Survival Manual
site_author: yigebande
nav:
  - 前言: index.md
  - 给高考生的话: To High School Graduate.md
  - 提问的智慧: How To Ask.md
  - 我个人的学习观点: Opinions On Study.md
  - 实用工具与技巧: 
    - Markdown: Powerful Tools And Techniques/Markdown.md
    - 盲打: Powerful Tools And Techniques/Touch Typing.md
    - Vim: Powerful Tools And Techniques/Vim.md
    - Git: Powerful Tools And Techniques/Git.md
    - LaTeX: Powerful Tools And Techniques/LaTeX.md
    - typst: Powerful Tools And Techniques/typst.md
    - AxMath: Powerful Tools And Techniques/AxMath.md
    - 视频编辑软件: Powerful Tools And Techniques/Video Editior.md
  - 数学工具: Math Tools/Tools For Mathematics.md
  - 画图工具: drawing/drawing.md
  - 大一:
    - 军理课: Freshman/junli.md
    - 高等数学: Freshman/gaoshu.md
    - 大学物理: Freshman/dawu.md
    - 程序设计: Freshman/Programming Design.md
    - 工程制图: Freshman/Engineering Drawing And CAD.md
    - 概率统计: Freshman/Probability And Statistics.md
    - 线性代数: Freshman/Linear Algebra.md
    - 理论力学: Freshman/Theoretical Mechanics.md
    - 航空航天与力学导论: Freshman/Introduction To Aerospace And Mechanics.md
  - 大二:
    - 机器智能: Sophomore/Machine Intelligence.md
    - 初级实用口译: Sophomore/Interpretation.md
    - 自动控制原理: Sophomore/Automatic Control Theory.md
    - 导弹飞行力学: Sophomore/Missile Flight Dynamics.md
    - 空间科学基础: Sophomore/Fundamental Space Science.md
    - 飞行器结构力学: Sophomore/Structural Mechanics Of Aircraft.md
    - 航天器轨道动力学: Sophomore/Orbital Mechanics.md
    - 数值计算方法: Sophomore/Method Of Numerical Computation.md
    - 科研创新训练: Sophomore/Research And Innovation Training.md
    - MATLAB及应用: Sophomore/Matlab And Applications.md
    - 空气动力学: Sophomore/Aerodynamics.md
    - 电子电工技术: Sophomore/Diangong.md
    - 工程热力学: Sophomore/Engineering Thermodynamics.md
    - 复变函数: Sophomore/Complex Functions.md
    - 机械设计基础: Sophomore/Basis Of Mechanical Design.md
    - 材料力学: Sophomore/Material Mechanics.md
    - 大学物理实验: Sophomore/General Physics Experiments.md
  - 大三:
    - 大三: Junior/index.md
  - 有趣的网站: Interesting Website.md
  - 三下乡: 3DownCountry/3DownCountry.md
  - 航院研究生毕业去向: After Graduation.md

repo_url: https://github.com/yigebande/SYSU-SAA-Survival-Manual
repo_name: SYSU-SAA-Survival-Manual

theme:
  name: material

  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yigebande/SYSU-SAA-Survival-Manual

plugins:
  # - git-revision-date
  